language: csharp
solution: Searchlight.sln

jobs:
  include:
    - dotnet: 2.1.502
      mono: none
      script:
        - dotnet build ./tests/Searchlight.Tests/netstandard20/Searchlight.Tests.netstandard20.csproj
        - dotnet test ./tests/Searchlight.Tests/netstandard20/Searchlight.Tests.netstandard20.csproj
